### ISSUE TITLE
Move OpenMetrics to a neutral github organization

### ISSUE THREAD

**Issue by caniszczyk** [RichiH/OpenMetrics#89]
OpenMetrics has enough TOC sponsors to enter the sandbox, we need to move it to a new github organization... any idea on names given that https://github.com/openmetrics is taken ?

**Comment by RichiH** [comment]
I am not opposed as such, but I don't see this requirement for GH, only for goverance and the like; can you link me to it, please? From what I can find, CNCF just requires admin access to the repo, which is not an issue; it makes most sense to add you, imo.

Orthogonal from that, I don't have a good name which would be free.

**Comment by caniszczyk** [comment]
We require the repo to live in a neutral org (can't be under your name), I'm trying to find the language in the charter that makes this clear.

I have https://github.com/open-metrics and just make you an owner :)

**Comment by RichiH** [comment]
Please do.

I also nagged OpenObservability, though that bites off more than I can currently chew.

**Comment by caniszczyk** [comment]
friendly ping on the repo move

**Comment by RichiH** [comment]
https://github.com/OpenObservability/OpenMetrics it is

**Comment by RichiH** [comment]
As long as we have many (partially stale) issues, I expect this repo still to be used, but going forward and for PR etc, the new place is the place to be.
